# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - ./sql:/data/sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  sql: